"""Shift-management handlers package (AUD3-06 4/4 split of shift_management.py).

Submodules register on the shared ``router`` (see _router.py) via decorators;
imported here in original top-to-bottom order = aiogram registration order.
"""
from ._router import router
from .shared import _format_end_label

from .auto_planning import (
    cmd_shifts,
    handle_shift_planning,
    handle_auto_planning,
    handle_auto_plan_week,
    handle_auto_plan_week_cancel,
    handle_auto_plan_week_confirm,
    handle_auto_plan_month,
    handle_auto_plan_month_cancel,
    handle_auto_plan_month_confirm,
    handle_auto_plan_tomorrow,
    handle_auto_plan_tomorrow_cancel,
    handle_auto_plan_tomorrow_confirm,
)
from .schedule import (
    handle_view_schedule,
    handle_schedule_date,
    handle_reassign_shift_pick,
    handle_reassign_executor,
    handle_schedule_week_view,
    handle_schedule_month_view,
    handle_back_to_shifts,
)
from .templates_a import (
    handle_template_management,
    handle_create_new_template,
    handle_view_all_templates,
    handle_template_name_input,
    handle_template_time_input,
    handle_template_duration_input,
    handle_edit_templates,
    handle_edit_template_details,
    handle_toggle_template_active,
    handle_edit_template_name,
    handle_edit_template_description,
    handle_edit_template_time,
    handle_edit_template_duration,
)
from .templates_b import (
    handle_template_create_specialization_toggle,
    handle_template_create_finish,
    handle_template_create_no_specs,
    handle_edit_template_specializations,
    handle_toggle_template_specialization,
    handle_save_template_specializations,
    handle_delete_template,
    handle_delete_template_confirm,
    handle_force_delete_template,
    handle_template_field_input,
)
from .manual_planning import (
    handle_create_shift_template,
    handle_template_selection,
    handle_date_selection,
    handle_weekly_planning,
    handle_weekly_planning_cancel,
    handle_weekly_planning_confirm,
)
from .analytics import (
    handle_shift_analytics,
    handle_shift_executor_assignment,
    handle_weekly_analytics,
    handle_workload_forecast,
    handle_optimization_recommendations,
    handle_monthly_analytics,
    handle_efficiency_analysis,
    handle_back_to_planning,
    handle_back_to_analytics,
)
from .assignment_a import (
    handle_assign_to_shift,
    handle_ai_assignment,
    handle_bulk_assignment,
    handle_workload_analysis,
    handle_redistribute_load,
    handle_schedule_conflicts,
)
from .assignment_b import (
    handle_bulk_auto_assign,
    handle_bulk_by_specialization,
    handle_bulk_by_period,
    handle_bulk_by_priority,
    handle_select_shift_for_assignment,
    handle_assign_executor_to_shift,
    handle_force_assign,
    handle_executor_assignment_back,
)

__all__ = [
    "router",
    "_format_end_label",
    "cmd_shifts",
    "handle_shift_planning",
    "handle_auto_planning",
    "handle_auto_plan_week",
    "handle_auto_plan_week_cancel",
    "handle_auto_plan_week_confirm",
    "handle_auto_plan_month",
    "handle_auto_plan_month_cancel",
    "handle_auto_plan_month_confirm",
    "handle_auto_plan_tomorrow",
    "handle_auto_plan_tomorrow_cancel",
    "handle_auto_plan_tomorrow_confirm",
    "handle_view_schedule",
    "handle_schedule_date",
    "handle_reassign_shift_pick",
    "handle_reassign_executor",
    "handle_schedule_week_view",
    "handle_schedule_month_view",
    "handle_back_to_shifts",
    "handle_template_management",
    "handle_create_new_template",
    "handle_view_all_templates",
    "handle_template_name_input",
    "handle_template_time_input",
    "handle_template_duration_input",
    "handle_edit_templates",
    "handle_edit_template_details",
    "handle_toggle_template_active",
    "handle_edit_template_name",
    "handle_edit_template_description",
    "handle_edit_template_time",
    "handle_edit_template_duration",
    "handle_template_create_specialization_toggle",
    "handle_template_create_finish",
    "handle_template_create_no_specs",
    "handle_edit_template_specializations",
    "handle_toggle_template_specialization",
    "handle_save_template_specializations",
    "handle_delete_template",
    "handle_delete_template_confirm",
    "handle_force_delete_template",
    "handle_template_field_input",
    "handle_create_shift_template",
    "handle_template_selection",
    "handle_date_selection",
    "handle_weekly_planning",
    "handle_weekly_planning_cancel",
    "handle_weekly_planning_confirm",
    "handle_shift_analytics",
    "handle_shift_executor_assignment",
    "handle_weekly_analytics",
    "handle_workload_forecast",
    "handle_optimization_recommendations",
    "handle_monthly_analytics",
    "handle_efficiency_analysis",
    "handle_back_to_planning",
    "handle_back_to_analytics",
    "handle_assign_to_shift",
    "handle_ai_assignment",
    "handle_bulk_assignment",
    "handle_workload_analysis",
    "handle_redistribute_load",
    "handle_schedule_conflicts",
    "handle_bulk_auto_assign",
    "handle_bulk_by_specialization",
    "handle_bulk_by_period",
    "handle_bulk_by_priority",
    "handle_select_shift_for_assignment",
    "handle_assign_executor_to_shift",
    "handle_force_assign",
    "handle_executor_assignment_back",
]
