[tool:pytest]
minversion = 6.0
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    --strict-markers
    --strict-config
    --verbose
    --tb=short
    --cov=app
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-fail-under=85

markers =
    unit: Unit tests
    integration: Integration tests
    api: API tests
    slow: Slow tests that take more than 1 second
    smoke: Smoke tests for basic functionality

asyncio_mode = auto

# Test discovery
testmon_datafile = .testmon/testmon.db

# Coverage configuration
[coverage:run]
source = app
omit =
    */tests/*
    */migrations/*
    */venv/*
    */env/*
    */conftest.py
    */test_*.py

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
    if __name__ == .__main__.:
    if TYPE_CHECKING:

[coverage:html]
directory = htmlcov