version: '3.8'

services:
  # Media Service API (Development)
  media-api:
    build: .
    container_name: uk_media_service_dev
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      # Database
      - DATABASE_URL=postgresql://media_user:media_password@media-db:5432/uk_media
      - DATABASE_ECHO=true  # Включено для разработки

      # Telegram
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHANNEL_REQUESTS=${CHANNEL_REQUESTS:--1003091883002}
      - CHANNEL_REPORTS=${CHANNEL_REPORTS:--1002969942316}
      - CHANNEL_ARCHIVE=${CHANNEL_ARCHIVE:--1002725515580}
      - CHANNEL_BACKUP=${CHANNEL_BACKUP:--1002951349061}

      # Application
      - DEBUG=true  # Включено для разработки
      - MAX_FILE_SIZE=52428800  # 50MB
      - ALLOWED_ORIGINS=*  # Разрешены все origins для разработки

      # Logging
      - LOG_LEVEL=DEBUG

    volumes:
      - ./app:/app/app:ro  # Bind mount для hot reload
      - ./client:/app/client:ro
      - ./logs:/app/logs

    depends_on:
      - media-db
      - media-redis

    networks:
      - media-network

    # Команда для разработки с автоперезагрузкой
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # PostgreSQL Database
  media-db:
    image: postgres:15-alpine
    container_name: uk_media_db_dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=uk_media
      - POSTGRES_USER=media_user
      - POSTGRES_PASSWORD=media_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C

    volumes:
      - media_db_dev_data:/var/lib/postgresql/data

    ports:
      - "5434:5432"

    networks:
      - media-network

  # Redis Cache
  media-redis:
    image: redis:7-alpine
    container_name: uk_media_redis_dev
    restart: unless-stopped
    command: redis-server --appendonly yes

    volumes:
      - media_redis_dev_data:/data

    ports:
      - "6381:6379"

    networks:
      - media-network

  # PgAdmin для разработки
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: uk_media_pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False

    ports:
      - "8082:80"

    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin

    depends_on:
      - media-db

    networks:
      - media-network

  # Redis Commander для разработки
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: uk_media_redis_commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:media-redis:6379

    ports:
      - "8083:8081"

    depends_on:
      - media-redis

    networks:
      - media-network

  # Frontend для тестирования
  frontend:
    build: ./frontend
    container_name: uk_media_frontend
    restart: unless-stopped
    ports:
      - "3002:80"

    depends_on:
      - media-api

    networks:
      - media-network

    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  media_db_dev_data:
    driver: local
  media_redis_dev_data:
    driver: local
  pgadmin_dev_data:
    driver: local

networks:
  media-network:
    driver: bridge
    name: uk_media_dev_network