# Alertmanager Configuration
# UK Management Bot - Sprint 19-22

global:
  resolve_timeout: 5m
  slack_api_url: 'YOUR_SLACK_WEBHOOK_URL'  # Replace with actual webhook

# Route tree for alert delivery
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default-receiver'

  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m

    # Warning alerts - batched notification
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 1h

# Alert receivers
receivers:
  # Default receiver
  - name: 'default-receiver'
    slack_configs:
      - channel: '#bot-gateway-alerts'
        title: 'Bot Gateway Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}'
        send_resolved: true

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    slack_configs:
      - channel: '#bot-gateway-critical'
        title: '🚨 CRITICAL: Bot Gateway'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Service:* {{ .CommonLabels.service }}
          *Description:*
          {{ range .Alerts }}
          {{ .Annotations.description }}
          {{ end }}
        send_resolved: true
    webhook_configs:
      - url: 'http://notification-service:8005/api/v1/webhooks/alerts'
        send_resolved: true

  # Warning alerts
  - name: 'warning-alerts'
    slack_configs:
      - channel: '#bot-gateway-warnings'
        title: '⚠️ Warning: Bot Gateway'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Service:* {{ .CommonLabels.service }}
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ end }}
        send_resolved: true

# Inhibition rules - suppress certain alerts when others fire
inhibit_rules:
  # Inhibit warning if critical is firing for same alert
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

  # Inhibit service errors if circuit breaker is open
  - source_match:
      alertname: 'CircuitBreakerOpen'
    target_match:
      alertname: 'HighServiceErrorRate'
    equal: ['service_name']
