"""add_missing_shift_fields_from_monolith

Revision ID: a4bc28241d88
Revises: 480bc2a7814b
Create Date: 2025-10-01 19:57:33.517784+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4bc28241d88"
down_revision: Union[str, None] = "480bc2a7814b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shifts",
        sa.Column(
            "planned_start_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Планируемое время начала",
        ),
    )
    op.add_column(
        "shifts",
        sa.Column(
            "planned_end_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Планируемое время окончания",
        ),
    )
    op.add_column(
        "shifts",
        sa.Column(
            "specialization_focus",
            sa.JSON(),
            nullable=True,
            comment='Массив специализаций ["electric", "plumbing"]',
        ),
    )
    op.add_column(
        "shifts",
        sa.Column(
            "coverage_areas",
            sa.JSON(),
            nullable=True,
            comment='Массив зон ["building_A", "yard_1"]',
        ),
    )
    op.add_column(
        "shifts",
        sa.Column(
            "geographic_zone", sa.String(length=100), nullable=True, comment="Географическая зона"
        ),
    )
    op.add_column(
        "shifts",
        sa.Column("max_requests", sa.Integer(), nullable=False, server_default="10", comment="Максимум заявок на смену"),
    )
    op.add_column(
        "shifts",
        sa.Column(
            "current_request_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Текущее количество заявок",
        ),
    )
    op.add_column(
        "shifts",
        sa.Column("completed_requests", sa.Integer(), nullable=False, server_default="0", comment="Завершенные заявки"),
    )
    op.add_column(
        "shifts",
        sa.Column(
            "average_completion_time",
            sa.Float(),
            nullable=True,
            comment="Среднее время выполнения (мин)",
        ),
    )
    op.add_column(
        "shifts",
        sa.Column(
            "average_response_time",
            sa.Float(),
            nullable=True,
            comment="Среднее время отклика (мин)",
        ),
    )
    op.alter_column(
        "shifts",
        "completion_rating",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Рейтинг качества (1.0-5.0)",
        existing_nullable=True,
    )
    op.alter_column(
        "shifts",
        "actual_duration_hours",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Фактическая продолжительность (часы)",
        existing_nullable=True,
    )
    op.alter_column(
        "shifts",
        "efficiency_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Эффективность (0-100)",
        existing_nullable=True,
    )
    op.create_index("idx_shifts_geographic_zone", "shifts", ["geographic_zone"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_shifts_geographic_zone", table_name="shifts")
    op.alter_column(
        "shifts",
        "efficiency_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Эффективность (0-100)",
        existing_nullable=True,
    )
    op.alter_column(
        "shifts",
        "actual_duration_hours",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Фактическая продолжительность (часы)",
        existing_nullable=True,
    )
    op.alter_column(
        "shifts",
        "completion_rating",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Рейтинг качества (1.0-5.0)",
        existing_nullable=True,
    )
    op.drop_column("shifts", "average_response_time")
    op.drop_column("shifts", "average_completion_time")
    op.drop_column("shifts", "completed_requests")
    op.drop_column("shifts", "current_request_count")
    op.drop_column("shifts", "max_requests")
    op.drop_column("shifts", "geographic_zone")
    op.drop_column("shifts", "coverage_areas")
    op.drop_column("shifts", "specialization_focus")
    op.drop_column("shifts", "planned_end_time")
    op.drop_column("shifts", "planned_start_time")
    # ### end Alembic commands ###
