"""initial schema

Revision ID: 001
Revises: 
Create Date: 2026-07-11 20:06:19.247157

"""
from alembic import op
import sqlalchemy as sa


revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('anomaly_rules',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('abs_threshold', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pct_change_threshold', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_window_months', sa.Integer(), nullable=False),
    sa.Column('avg_deviation_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'resource_type', name='uq_anomaly_rules')
    )
    op.create_table('launch_tickets',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('external_user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('object_types',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_object_types_tenant_name')
    )
    op.create_table('providers',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('export_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_providers_tenant_name')
    )
    op.create_table('reporting_periods',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'month', name='uq_periods_tenant_month')
    )
    op.create_table('tags',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tags_tenant_name')
    )
    op.create_table('users',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_id', name='uq_users_tenant_external')
    )
    op.create_table('audit_log',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['tenant_id', 'entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('exports',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_correction', sa.Boolean(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_by', sa.Uuid(), nullable=True),
    sa.Column('sent_channel', sa.String(length=100), nullable=True),
    sa.Column('sent_comment', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exports_lookup', 'exports', ['tenant_id', 'reporting_period_id', 'provider_id'], unique=False)
    op.create_table('resource_objects',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('type_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['resource_objects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['object_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_rows',
    sa.Column('export_id', sa.Uuid(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meters',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('meter_number', sa.String(length=100), nullable=False),
    sa.Column('meter_number_normalized', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('install_location', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('primary_object_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('provider_account', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('coefficient', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('max_digits', sa.Integer(), nullable=True),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('removed_at', sa.Date(), nullable=True),
    sa.Column('replaces_meter_id', sa.Uuid(), nullable=True),
    sa.Column('photo_file_id', sa.String(length=300), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_object_id'], ['resource_objects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['replaces_meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meters_primary_object', 'meters', ['tenant_id', 'primary_object_id', 'resource_type'], unique=False)
    op.create_index('uq_meters_active_number', 'meters', ['tenant_id', 'meter_number_normalized'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.create_table('object_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['resource_objects.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'tag_id', name='uq_object_tags_pair')
    )
    op.create_table('meter_object_links',
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allocation_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['resource_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'object_id', 'link_type', name='uq_meter_object_links')
    )
    op.create_index('ix_meter_object_links_object', 'meter_object_links', ['object_id', 'link_type'], unique=False)
    op.create_table('meter_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'tag_id', name='uq_meter_tags_pair')
    )
    op.create_table('readings',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('meter_id', sa.Uuid(), nullable=False),
    sa.Column('reporting_period_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('read_at', sa.Date(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('previous_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('consumption', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('missing_reason', sa.String(length=30), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('photo_file_id', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_periods.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'reporting_period_id', name='uq_readings_meter_period')
    )
    op.create_index('ix_readings_period_status', 'readings', ['reporting_period_id', 'status'], unique=False)
    op.create_table('reading_revisions',
    sa.Column('reading_id', sa.Uuid(), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_revisions')
    op.drop_index('ix_readings_period_status', table_name='readings')
    op.drop_table('readings')
    op.drop_table('meter_tags')
    op.drop_index('ix_meter_object_links_object', table_name='meter_object_links')
    op.drop_table('meter_object_links')
    op.drop_table('object_tags')
    op.drop_index('uq_meters_active_number', table_name='meters', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_meters_primary_object', table_name='meters')
    op.drop_table('meters')
    op.drop_table('export_rows')
    op.drop_table('resource_objects')
    op.drop_index('ix_exports_lookup', table_name='exports')
    op.drop_table('exports')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('reporting_periods')
    op.drop_table('providers')
    op.drop_table('object_types')
    op.drop_table('launch_tickets')
    op.drop_table('anomaly_rules')
    op.drop_table('tenants')
    # ### end Alembic commands ###
