# Prometheus Configuration for Bot Gateway Service
# UK Management Bot - Sprint 19-22

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'uk-management-bot'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Bot Gateway Service
  - job_name: 'bot-gateway'
    static_configs:
      - targets: ['bot-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Request Service
  - job_name: 'request-service'
    static_configs:
      - targets: ['request-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Shift Service
  - job_name: 'shift-service'
    static_configs:
      - targets: ['shift-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Analytics Service
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # AI Service
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8007']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Integration Service
  - job_name: 'integration-service'
    static_configs:
      - targets: ['integration-service:8009']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Cadvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
